site.title: Site title
site.tagline: Some clever tagline here
site.author: Author Name

# Optional google analytics tracking code
site.ga_tracking_id: 'UA-XXXXXXXX-1'

# A valid PHP timezone
# http://php.net/manual/en/timezones.php
site.timezone: America/Chicago

# The default date formatting when displaying post dates
# http://php.net/manual/en/function.date.php
site.date_format: 'F dS, Y'

# https://support.google.com/webmasters/answer/35624?hl=en#1
site.meta_description: ContentItem of meta description goes here

path.content: %path.base%/content

http_cache.enabled: true
http_cache.default_ttl: 3600

debug: false