# You can override configurations from default.yml here
# These configs will only take effect in the 'prod' environment.
# Keep in mind that production (prod) is the default environment.
# So if you haven't created a .env file, or your .env file sets the
# APP_ENV to prod, then this will be read. If you provide
# a config that matches a config from default.yml, the config
# in this file will take precedence.
#
# If you want to change the environment on this machine to prod
# you have to rename .env.example to .env and set the APP_ENV to prod.
#
# Your production server and your dev server should have two
# different ".env" files. That is why the file is ignored by git.
#
# If you are not using a ".env" file or don't care what
# environment the app is in, then this does not apply to you.
#
# https://github.com/vlucas/phpdotenv
debug: true