-
  key: categories
  name: Category
  plural_name: Categories
  slug: category
  terms:
    -
      name: Web Development
      slug: web-development
    -
      name: foo BAR baz
      slug: foo-bar-baz
-
  key: tags
  name: Tag
  plural_name: Tags
  slug: tag
  terms:
    -
      name: Tag1
      slug: tag1
    -
      name: Tag2
      slug: tag2